<?php


namespace Tir\Authorization\Providers;


use Illuminate\Console\Events\CommandFinished;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Str;
use Symfony\Component\Console\Output\ConsoleOutput;
use Tir\Authorization\Database\Seeders\DatabaseSeeder;
use Tir\Crud\Providers\CrudSeedServiceProvider;

class SeedServiceProvider extends CrudSeedServiceProvider
{
    public function boot()
    {
        $this->seeders = [
            DatabaseSeeder::class
        ];
        parent::boot(); // TODO: Change the autogenerated stub
    }

}